version: "3.7"

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongo:/data/db
    networks:
      - cuckoo
    
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    networks:
      - cuckoo
    
  cuckoo:
    build: .
    image: cuckoo:ubuntu
    ports:
      - "80:8000"
    container_name: cuckoo
    restart: always
    env_file:
      - variables.env
    depends_on:
      - mongo
      - postgres
    volumes:
      - cuckoo:/opt/cuckoo/
    networks:
      - cuckoo

networks:
  cuckoo:
    
volumes:
  mongo:
  postgres:
  cuckoo:
